### ISSUE TITLE
animated text

### ISSUE THREAD

**Issue by DevAnyKR** [DevAnyKR/StreamDock.Plugin.GoogleAPI#18]
GoogleCalendar 일정 제목 문자열이 길 경우 내용을 알기 어려움

### 움직임 효과를 적용했을 때

https://github.com/DevAnyKR/StreamDock.Plugin.GoogleAPI/assets/110871727/f2632dd0-02be-429f-bc62-eaa264cba002

**Comment by DevAnyKR** [comment]
되긴 되는데...🤣

**Comment by thiat1998** [comment]
![image](https://github.com/DevAnyKR/StreamDock.Plugin.GoogleAPI/assets/112832077/6c9842d4-2ddd-40b7-aad8-fa78027bc40b)

현재 이러한 상태입니다
표현이 안되어지네요 어떤 문제일까요..ㅠㅠ?
json 파일도 bin에 재대로 잘 되어있고

%AppData%\DevAny\StreamDock.Plugins\GoogleAPI
경로 파일도 삭제했습니다

**Comment by DevAnyKR** [comment]
@thiat1998 
키를 눌러도 인증 창이 나타나지 않나요?
API가 추가된 것이 아니기 때문에 토큰 파일을 삭제하지 않아도 됩니다.
코드가 아직 불안정합니다. 작동이 안 되면 이전 릴리즈 버전을 사용해주세요.😅
아무래도 캘린더 전용 플러그인을 따로 만들어야겠습니다. ㅠ

**Comment by thiat1998** [comment]
> @thiat1998 키를 눌러도 인증 창이 나타나지 않나요? API가 추가된 것이 아니기 때문에 토큰 파일을 삭제하지 않아도 됩니다. 코드가 아직 불안정합니다. 작동이 안 되면 이전 릴리즈 버전을 사용해주세요.😅 아무래도 캘린더 전용 플러그인을 따로 만들어야겠습니다. ㅠ

네 ㅠㅠ 키를 눌러도 나오질 않더구요..
아쉽습니다 스크롤기능 설랬었는데ㅠㅠ

**Comment by DevAnyKR** [comment]
@thiat1998 동작 환경이 어떻게 되나요? OS 버전, 백신 등...
제껀 잘 되는데, 실험 환경이 한정적이라 원인을 찾기 어렵습니다.😅
이런것 때문에 협업이 필요해요;; 

제 스트림독은 메모리 사용량이 전혀 동작하지 않아요. 장치나 환경마다 기능 동작이 다른가봐요.

**Comment by thiat1998** [comment]
> @thiat1998 동작 환경이 어떻게 되나요? OS 버전, 백신 등... 제껀 잘 되는데, 실험 환경이 한정적이라 원인을 찾기 어렵습니다.😅 이런것 때문에 협업이 필요해요;;
> 
> 제 스트림독은 메모리 사용량이 전혀 동작하지 않아요. 장치나 환경마다 기능 동작이 다른가봐요.

windows11 64bit / 백신X / ajazz akp153e / 소프트웨어버전 2.9.177.122 입니다 ㅠ
